version: "3.9"

services:
  node-docker:
    container_name: node-docker
    tty: true               # remove for `entrypoint` in Dockerfile
    stdin_open: true        # remove for `entrypoint` in Dockerfile
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - "8000:8000"
